const products = [
  {
    id: 1,
    name: "T-shirt Homme",
    type: "clothes",
    price: 19.99,
    quantity: 50,
    image: `tshirt-removebg.png`,
  },
  {
    id: 2,
    name: "Sweat pour Femme",
    type: "clothes",
    price: 39.99,
    quantity: 30,
    image: `sweat-removebg.png`,
  },
  {
    id: 3,
    name: "Jeans Slim",
    type: "clothes",
    price: 49.99,
    quantity: 20,
    image: `jeans-removebg.png`,
  },
  {
    id: 4,
    name: "Sac à dos",
    type: "accessorys",
    price: 29.99,
    quantity: 15,
    image: `sacados-removebg.png`,
  },
  {
    id: 5,
    name: "Montre Connectée",
    type: "electronics",
    price: 89.99,
    quantity: 40,
    image: `montre-removebg.png`,
  },
  {
    id: 6,
    name: "Casque Bluetooth",
    type: "electronics",
    price: 59.99,
    quantity: 25,
    image: `casque-removebg.png`,
  },
  {
    id: 7,
    name: "Lampe LED",
    type: "electronics",
    price: 15.99,
    quantity: 100,
    image: `led-removebg.png`,
  },
  {
    id: 8,
    name: "Chaussures de Course",
    type: "accessorys",
    price: 65.99,
    quantity: 60,
    image: `chaussure-removebg.png`,
  },
  {
    id: 9,
    name: "Portefeuille en Cuir",
    type: "accessorys",
    price: 39.99,
    quantity: 10,
    image: `portefeuille-removebg.png`,
  },
  {
    id: 10,
    name: "Montre Analogique",
    type: "electronics",
    price: 29.99,
    quantity: 35,
    image: `montreanalogique-removebg.png`,
  },
];
export default products;
